import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/users" className={styles.card}>
            <h2>Users &rarr;</h2>
            <p>10 Users</p>
          </a>

          <a href="/posts" className={styles.card}>
            <h2>Posts &rarr;</h2>
            <p>100 Posts</p>
          </a>

          <a href="/albums" className={styles.card}>
            <h2>Albums &rarr;</h2>
            <p>100 Albums</p>
          </a>
          <a href="/todos" className={styles.card}>
            <h2>Todos &rarr;</h2>
            <p>200 Todos</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
